-Xrs
-Xms512m
-Xmx2048m
-Xss384k
-XX:MetaspaceSize=96m
-XX:MaxMetaspaceSize=160m
-XX:MaxDirectMemorySize=512m
-XX:NewRatio=3
-XX:SurvivorRatio=30
-XX:MinHeapFreeRatio=20
-XX:MaxHeapFreeRatio=80
-verbose:gc
-XX:+PrintGCDetails
-XX:+PrintGCDateStamps
-XX:+UseConcMarkSweepGC
-XX:+UseCMSInitiatingOccupancyOnly 
-XX:CMSInitiatingOccupancyFraction=85
-XX:+ScavengeBeforeFullGC 
-XX:+CMSScavengeBeforeRemark
-Dsun.net.inetaddr.ttl=3600
-Dnetworkaddress.cache.ttl=3600
-Dsun.net.inetaddr.negative.ttl=300
-Dnetworkaddress.cache.negative.ttl=300
-Dsun.nio.PageAlignDirectMemory=true
-Djava.net.preferIPv4Stack=true
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-Djava.util.logging.config.file=conf/logging.properties
-Dtc.work.path=work
-Dtc.log.path=logs
-Djavax.servlet.context.tempdir=work
#-Dcom.sun.management.jmxremote
#-Dcom.sun.management.jmxremote.port=10010
#-Dcom.sun.management.jmxremote.rmi.port=10011
#-Dcom.sun.management.jmxremote.ssl=false
#-Dcom.sun.management.jmxremote.authenticate=false